ktor:
  application:
    modules:
     - com.github.fatalistix.ApplicationKt.module
  deployment:
    port: $MANAGER_PORT

application:
  alphabet: "abcdefghijklmnopqrstuvwxyz1234567890"
  actor:
    count: 5
  worker:
    response:
      timeout: 200s
    acquire:
      timeout: 200s
