ktor:
  application:
    modules:
     - com.github.fatalistix.ApplicationKt.module
  deployment:
    port: 8080

application:
  alphabet: "abcdefghijklmnopqrstuvwxyz1234567890"
  actor:
    count: 5
    response:
      timeout: 200s
