ktor:
  application:
    modules:
     - com.github.fatalistix.ApplicationKt.module
  deployment:
    port: $MANAGER_PORT

application:
  alphabet: "abcdefghijklmnopqrstuvwxyz1234567890"
  actor:
    count: 5
  worker:
    response:
      timeout: 200s
    acquire:
      timeout: 200s
  mongo:
    connection: $APPLICATION_MONGO_CONNECTION
    database: $APPLICATION_MONGO_DATABASE
    write:
      timeout: 5s
  rabbitmq:
    host: $APPLICATION_RABBITMQ_HOST
    port: $APPLICATION_RABBITMQ_PORT
    username: $APPLICATION_RABBITMQ_USERNAME
    password: $APPLICATION_RABBITMQ_PASSWORD
    reconnect:
      delay: 5s
    task:
      exchange:
        name: $APPLICATION_RABBITMQ_TASK_EXCHANGE_NAME
      message:
        expiration: 200s
    result:
      exchange:
        name: $APPLICATION_RABBITMQ_RESULT_EXCHANGE_NAME
